#---------------------------------------------------------------------

# This file was generated by Image2PyFile_GUI.py

from wx.lib.embeddedimage import PyEmbeddedImage

catalog = {}
#---------------------------------------------------------------------

Play_png = PyEmbeddedImage( 
    "iVBORw0KGgoAAAANSUhEUgAAADQAAAAXCAYAAABEQGxzAAAABHNCSVQICAgIfAhkiAAABjNJ"
    "REFUWIXdmGuMFFUWx3/V3cyjYYfhgxPIqkNklRiT1TVxI1FxAuFhCCAwhlFA1zWuiSIxupJd"
    "xXXXYHCzGh8f3KxuNkZEjTrCIi4LAWxdFl9fTDQ4S4wwOMMM8+jp7pmurrr1uPvhVlXf6q4Z"
    "+LKPeJLKrbp1zr3nf885/zrdhpFK832SzPko+Z4n/9OOnK+k0mljqvfGZBH6fwKhi21CaQLy"
    "ebj8inpwiYBqwTgWCAG+H0xIkMFS+opSew4XMGrma211vXNJKqXGQgHODIDjwPU3xkHVAdLB"
    "WOMwUQbXCxzRN9a90ecS0MTsagEmrZewti/BMCBlKCCFIoyMgJSweFkVVAyQDmZsCCYm6n1u"
    "n5eLPWezJvMvO8mmDX9l3dqDkUH7j3L0ftMBBhhBVGJ+6gvXoksIr4FyXgbvXBfGxuDsMAgb"
    "1nUpUBEp6GAGvwOzHJxKwj7fHO+InifGp/Pxpz9h+1ObKRSms2nD7kjfETXGRv0B6X7r2CTx"
    "g9D3D0FlmyFtwMAAvPyiJ+++N23EWc6H/l4olUhOp2BO2NXphoYyHTccpXVmnq2PbKOrc3dk"
    "agd6hnbSUtbX1TlTMrQLRgyQvrqamlRtD5xRqindbqQfxkaVI0K7bAEiIAZQo7CVnmOr50vn"
    "nWBwsC2aAxUhJ9A9c2YWjz/xAFdfe4DrFu3md9sfoFBsRAhYv/FFDh25NtrPEdU9vvxqHh1L"
    "3qZSTkfvHAtcR12N0xSo/JgGyB/3ZHkIhobBsqpOhlf0bFcjVL/xpbS1DUVzkZ6lxlvveInL"
    "53/NoX0r2fnnuymVsjz3wi8QNqxf183O1zure4aHKWDXm2tZs2ovvu9Fa4U6jq2ilELR+B+e"
    "9GQKoFRUBWaOg23Fo+PU3EeOBosW8lmO5Bbw6G9/Q+fN3ZF+qBdGaPcbt7B00QEMQ9DaMsKD"
    "m5/lcK4DIWDhghwnT7XT86+5kb0jYHi4hSO5haxc9l4dECEU2wmhImWaUBgLSMG2wKqAZauX"
    "US7X0KcRJPb1S3LRXFNjhbntp9jU9SrLl+zH1ohA2CrfbauBV3bdSe5oB8MjF+D7mWA9H8cC"
    "icfqFXt48+1OHt7ydFRke95bwYKfHmN6tqCiHtafRhRhWjuOGjMAFRPsSoDeoY5qI4ABuAPd"
    "HfU0TDWCESChdJ7/4xYKhVk8tvUxLprTR1OzheulWXHLYexAZ9mifdy1eSc/u/VlZrYUcf0U"
    "e/bdzLaHH49SmASf7CBqnqt8zwAUC2AGgFxXA0DyF1yIhMkEcYJT/cexG/nTcxuZ+YOisrdh"
    "cKgtdgjNTUUWXPMRe/evZP2a1zj22XW0zsxzycU9MVbVRQLlMozmoWyqtEsBnB1S+RcWpR0w"
    "mmvHCSFWG/q8NobzUCUEx2nAd91YPR48sjw6nJA8blrczd8OrsY00+zdv5abFr8bq2edLIRQ"
    "mTU6Cqd6oVhUjUAKYGln2pgoV/PRdap0bWtOhh9KITRqD947wRimQHj6QsCVV3zGX167j9HR"
    "FoqlZt4/uJpTvZdEhxM6OKftJHNmn+b1d+6kr7+da676IM6y4b2lSmS8BKf74Lt+lVm7urUP"
    "a2FMpVc6XS1+IynfAicMmLJXC4ED3NH1NK+88RD3/eotMhmHq398lJ/f9hSff3GDol7NfunC"
    "d3j2pR2sWvYq0nNxvPp1pYRKBfoH4XiP+ga1toQ+B73c7x/1pOtCYwPMyFY72zpQIYiAOHRm"
    "kKG+1sfEOoMaFomAaC2D42a4f9v77Pj1Bma1jlSVAjtfKjYeOAtf9sDJ06ph/eqE6uVizem2"
    "LZ6UEqY3Qzar+iQjXcUR94K60NQ1yVP0NIasggxtzMoMPvpkNfnCbG5b80xMXwK+B5aAwSE4"
    "fgJ6+9SBzb0I/v5hAiCArfd40vVgWgaam9SVTiU3lbWSlHbnK7/cnmNaxmL+vM/pWrWDpkYz"
    "WlT6qkYmyjCch29PQ9+AAnPxD+HQPyf5+RDKvRs9WRpXaZdtUnUlJ4vMVO1zUhdaqzOZbY1M"
    "mDA0AsOjUCor3y6cDYc/PscPvFBuX+XJkqny1ayAcKof1v+2SKn2NyuqhmZk4Yue5P8WJgWk"
    "y/rlnrTE/xaQ6ypQhz+d+k+SfwOm+MnruNSQXgAAAABJRU5ErkJggg=="
    )

catalog["Play.png"] = "Play_png"
GetData_Play_png   = Play_png.GetData
GetImage_Play_png  = Play_png.GetImage
GetBitmap_Play_png = Play_png.GetBitmap
GetIcon_Play_png   = Play_png.GetIcon
